export type PostKind = "passenger" | "driver" | "other";

const CYR_TO_LATIN: Record<string, string> = {
  "\u0430": "a", "\u0431": "b", "\u0432": "v", "\u0433": "g", "\u0434": "d",
  "\u0435": "e", "\u0451": "e", "\u0436": "j", "\u0437": "z", "\u0438": "i",
  "\u043A": "k", "\u043B": "l", "\u043C": "m", "\u043D": "n", "\u043E": "o",
  "\u043F": "p", "\u0440": "r", "\u0441": "s", "\u0442": "t", "\u0443": "u",
  "\u0444": "f", "\u0445": "x", "\u0446": "c", "\u0447": "ch", "\u0448": "sh",
  "\u0449": "sh", "\u044A": "", "\u044B": "i", "\u044C": "", "\u044D": "e",
  "\u044E": "yu", "\u044F": "ya", "\u0439": "y", "\u045E": "o", "\u049B": "q",
  "\u0493": "g", "\u04B3": "h", "\u2019": "'", "\u02BC": "'", "\u2018": "'",
};

export function toLatin(text: string): string {
  let out = "";
  for (const ch of (text ?? "").toLowerCase()) {
    out += CYR_TO_LATIN[ch] ?? ch;
  }
  return out;
}

const DRIVER_PATTERNS: RegExp[] = [
  /odam\s*lar?\s*ol/i,
  /odam\s+(ol|to[']pla|yig)/i,
  /(^|\s)(odam[iy]?|imiz|im|iz|lar)\s+kam\b/i,
  /odam\s+bormi/i,
  /odam\s+(bo[']lsa|borsa)\b/i,
  /kam\s+odam/i,
  /kamdimiz/i,
  /kamdamiz/i,
  /kam\s+bord[iy]?miz/i,
  /olamiz/i,
  /olamz\b/i,
  /olaman\b/i,
  /olib\s+(ber|yur|chiq|ket(aman|adi|am|moqchi))/i,
  /yo[']lovchi\s*lar?\s*ol/i,
  /yo[']lovchi\s*(bormi|bo[']lsa|borsa|kerak|kam|qidir|izla)/i,
  /pochta\s*lar?\s*ol/i,
  /(odam|pochta|posilka)\s+o[́']?lam[iy]z?/i,
  /joy\s+bor\b/i,
  /joy\s+bosh\b/i,
  /joy\s+qol(di|gan)?\s*(bormi)?/i,
  /oldi\s+(bosh|bo[']sh)/i,
  /bosh\s+joy/i,
  /bo[']sh\s+joy/i,
  /to[']ld[iy]/i,
  /tashuvchi/i,
  /haydovchi/i,
  /xaydovchi/i,
  /mashina\s+bor\b/i,
  /avto\s+(bor|bush)/i,
  /avto\s*(kob|kobal|cobalt|nexia|gentra|lacetti|matiz|moshina)/i,
  /\b(cobalt|kobal[dt]|nexia|matiz|gentra|lacetti|damas|spark|moshina)\b(\s+\d+\s*(места|место|joy|бор)?|\s+(бор|bush|буш|бос|bosh)\b)?/i,
  /tom\s+bagaj/i,
  /mijoz\s*(bormi|kerak|kam|bo[']lsa|borsa|qidir|izla)/i,
  /xaridor/i,
  /passajir/i,
  /pasajir/i,
  /boradigan\s+(odam|yo[']lovchi|mijoz)/i,
  /mol\s+(ol|tashiy)|tashiy/i,
  /tovar|yuk\s+/i,
  /shahar\s+(ichida|ichiga|ichdan)\s+(ol|qatna|aylan)/i,
  /shaxar\s+(ichida|ichiga|ichdan)\s+(ol|qatna|aylan)/i,
  /qo[']ng[']iroq\s+(qil|ber)\w*\s+(o[']lish|olish)/i,
  /non\s+top/i,
  /reys\s+qidir/i,
  /yo[']l\s+(ber|top|qil)/i,
  /mashina\s+top/i,
  /avtomashina\s+bor/i,
];

const PASSENGER_PATTERNS: RegExp[] = [
  /ketaman\b/i,
  /boraman\b/i,
  /borayapman\b/i,
  /boryapman\b/i,
  /ketayotgan\s+bor/i,
  /boradigan\s+bor/i,
  /ketadigan\s+bor/i,
  /qatnaydigan\s+bor/i,
  /yuradigan\s+bor/i,
  /kim\s+(bor|ket|bar)/i,
  /joy\s+bormi/i,
  /joy\s+(qidi|izla)/i,
  /joy\s+kerak/i,
  /o[']rin\s+(kerak|qidi|izla|borm)/i,
  /olib\s+ketadigan\s+kerak/i,
  /menga\s+(joy|o[']rin)/i,
  /men\s+(ham\s+)?(boraman|ketaman|borayapman|boryapman)/i,
  /biz\s+(ham\s+)?ketamiz/i,
  /biz\s+(ham\s+)?boramiz/i,
  /biz\s+(ham\s+)?yuramiz/i,
  /qidiryapman/i,
  /izlayapman/i,
  /odam\s+bor\b/i,
  /odam\s+(topil|chiq)\w*/i,
  /odam\s+(boradigan|ketadigan|qatnaydigan|yuradigan)\s+bor/i,
  /yo[']lovchi\s+bor\b/i,
  /mijoz\s+(bor|topil|chiq)/i,
  /erta\s+(ketish|borish|chiqish)\s+bor/i,
  /borish\s+kerak/i,
  /ketish\s+kerak/i,
  /(borish|ketish|qaytish)\s+[kк][kк]\b/i,
  /chiqish(i)?m?\s+(kerak|kk|bor)/i,
  /chiqayapman\b/i,
  /chiqaman\b/i,
  /yo[']l\s+(izlay|qidi)/i,
  /transport\s+(qidi|kerak)/i,
  /sayohat/i,
  /safarga/i,
  /yuramiz\b/i,
  /ketamiz\b/i,
  /boramiz\b/i,
  /yuraman\b/i,
  /boraman\b/i,
  /ketaman\b/i,
  /chiqaman\b/i,
  /chiqamiz\b/i,
  /qaytamiz\b/i,
  /qaytaman\b/i,
  /\d+\s*[-—]*\s*odom\s*kam\b/i,
  /\d+\s*[-—]*\s*odam\s*kam\b/i,
  /\d+\s*(ta|tacha|dona)\s+kam\b/i,
  /(ketish|borish|chiqish|yurish)\s+kerak/i,
  /(ketish|borish|chiqish|yurish)\s+kim/i,
  /kim\s+bor/i,
  /kim\s+ket/i,
  /kim\s+yur/i,
  /ketadigan\s+kim/i,
  /boradigan\s+kim/i,
  /yuradigan\s+kim/i,
  /odam\s+qidir/i,
  /odam\s+izla/i,
  /joy\s+qidir/i,
  /joy\s+izla/i,
  /joy\s+kerak/i,
  /o[']rin\s+kerak/i,
  /oldim\s+kerak/i,
  /oldi\s+kerak/i,
  /(ertaga|ertalab|bugun|hozir)\s+(ketaman|boraman|yuraman|chiqaman)/i,
  /(ertaga|ertalab|bugun|hozir)\s+(ketamiz|boramiz|yuramiz|chiqamiz)/i,
  /(ertaga|ertalab|bugun|hozir)\s+(ketish|borish|chiqish|yurish)/i,
  /kerak\s+(ketish|borish|chiqish|yurish)/i,
  /kerak\s+(odam|yo[']lovchi)/i,
];

export function classifyPostKind(text: string): PostKind {
  const t = toLatin(text);
  if (DRIVER_PATTERNS.some((re) => re.test(t))) return "driver";
  if (PASSENGER_PATTERNS.some((re) => re.test(t))) return "passenger";
  return "other";
}
